Disabling parallel build on Windows The /m option might be the cause for a "fatal error C1060: compiler is out of heap space" error we get duruing a Packer build